#how to use this file to set parameters https://carpentries-incubator.github.io/jekyll-pages-novice/starting-jekyll/#:~:text=Jekyll's%20main%20configuration%20options%20are,every%20page%20of%20your%20website.
description: "This is my personal website."
email: "vmwhite@wisc.edu"